// generatePets.js
// Auto-generate pets for Veterinary Clinic Project
// Each owner gets 1-3 pets randomly
//This section is generated by AI for the purpose of adding dummy data to the database.

const mysql = require("mysql2/promise");
const { faker } = require("@faker-js/faker");

// ==== MODIFY BELOW FOR YOUR DB ====
const dbConfig = {
    host: "localhost",
    user: "root",
    password: "wjy000908",  // Change this
    database: "vet_clinic",
};
// ==================================

// Expanded breed lists
const breedMap = {
    Dog: [
        "Labrador Retriever","Golden Retriever","German Shepherd","Poodle","Bulldog","Beagle","Rottweiler",
        "Yorkshire Terrier","Boxer","Dachshund","Siberian Husky","Shih Tzu","Doberman Pinscher",
        "Australian Shepherd","Corgi","Chihuahua","Great Dane","Border Collie","Pomeranian",
        "Cocker Spaniel","Maltese","Bernese Mountain Dog","Basset Hound","Pit Bull Terrier",
        "Akita","Shiba Inu","Havanese","Weimaraner","Newfoundland","Sheltie","Greyhound",
        "Whippet","Boston Terrier","Cane Corso","Vizsla","Samoyed"
    ],
    Cat: [
        "Siamese","Persian","Maine Coon","British Shorthair","Sphynx","Bengal","Ragdoll",
        "Russian Blue","Scottish Fold","Abyssinian","American Shorthair","Himalayan",
        "Birman","Oriental Shorthair","Norwegian Forest Cat","Savannah","Devon Rex",
        "Cornish Rex","Tonkinese","Balinese","Manx","Chartreux","Turkish Angora","Bombay"
    ],
    Bird: [
        "Parrot","Macaw","Cockatiel","Canary","Finch","Lovebird","Budgerigar","African Grey",
        "Cockatoo","Parakeet","Sun Conure","Pionus Parrot","Quaker Parrot"
    ],
    Rabbit: [
        "Holland Lop","Mini Rex","Lionhead","Dutch Rabbit","Flemish Giant","Netherland Dwarf",
        "Harlequin","English Lop","Mini Lop","Angora Rabbit","Silver Fox","Rex Rabbit",
        "Californian Rabbit"
    ]
};

// Expanded colors
const colors = [
    "Black","White","Brown","Light Brown","Chocolate","Golden","Cream","Gray","Dark Gray","Silver",
    "Tan","Orange","Red","Blue-gray","Brindle","Spotted","Patchy","Mixed Color","Calico","Tabby",
    "Tortoiseshell","Sable","Copper","Lilac","Fawn"
];

// Expanded allergies list
const allergiesList = [
    "None","Pollen","Dust Mites","Grass","Fleas","Beef Allergy","Chicken Allergy","Dairy Allergy",
    "Grain Allergy","Corn Allergy","Peanut Allergy","Soy Allergy","Seafood Allergy","Shampoo Allergy",
    "Plastic Allergy","Latex Allergy","Seasonal Allergy","Environmental Allergy"
];

async function generatePets() {
    console.log("Connecting to DB...");
    const connection = await mysql.createConnection(dbConfig);

    // Get all owner IDs
    const [owners] = await connection.query("SELECT ownerID FROM owners");
    const ownerIDs = owners.map(o => o.ownerID);

    let petsToInsert = [];

    // Each owner gets 1-3 pets (weighted toward 1-2)
    for (const ownerID of ownerIDs) {
        // 70% get 1 pet, 25% get 2 pets, 5% get 3 pets
        const rand = Math.random();
        let petCount;
        if (rand < 0.70) {
            petCount = 1;
        } else if (rand < 0.95) {
            petCount = 2;
        } else {
            petCount = 3;
        }

        for (let i = 0; i < petCount; i++) {
            const type = faker.helpers.arrayElement(Object.keys(breedMap));
            const breed = faker.helpers.arrayElement(breedMap[type]);
            const gender = faker.helpers.arrayElement(["Male", "Female"]);
            const color = faker.helpers.arrayElement(colors);
            const allergies = faker.helpers.arrayElement(allergiesList);

            petsToInsert.push([
                ownerID,
                faker.person.firstName(),
                type,
                breed,
                faker.number.int({ min: 1, max: 20 }),
                gender,
                color,
                allergies
            ]);
        }
    }

    console.log(`Inserting ${petsToInsert.length} pets...`);

    const sql = `
        INSERT INTO Pets
        (ownerID, name, type, breed, age, gender, color, allergies)
        VALUES ?
    `;

    await connection.query(sql, [petsToInsert]);

    console.log(`✓ ${petsToInsert.length} pets mock data inserted successfully!`);
    await connection.end();
}

generatePets().catch(console.error);