// generateStaff.js
// Auto-generate 1000 staff members for Veterinary Clinic Project
// Veterinarians dominate (60%)
// This section is generated by AI for the purpose of adding dummy data to the database base on Generateowners.js.

const mysql = require("mysql2/promise");
const { faker } = require("@faker-js/faker");

// ==== MODIFY BELOW FOR YOUR DB ====
const dbConfig = {
    host: "localhost",
    user: "root",
    password: "wjy000908",  // Change this
    database: "vet_clinic",
};
// ==================================

const positions = [
    "Veterinarian",
    "Technician",
    "Assistant",
    "Receptionist",
    "Manager"
];

// Position weights (must sum to 1.0)
const positionWeights = {
    "Veterinarian": 0.60,   // 60%
    "Technician": 0.20,     // 20%
    "Assistant": 0.10,      // 10%
    "Receptionist": 0.08,   // 8%
    "Manager": 0.02         // 2%
};

const vetSpecialties = [
    "General Medicine",
    "Surgery",
    "Dermatology",
    "Dentistry",
    "Radiology",
    "Emergency Care",
    "Nutrition",
    "Behavior",
    "Other"
];

const techSpecialties = [
    "Radiology",
    "General Medicine",
    "Other"
];

function weightedRandom(weights) {
    const rand = Math.random();
    let cumulative = 0;
    
    for (const [key, weight] of Object.entries(weights)) {
        cumulative += weight;
        if (rand < cumulative) {
            return key;
        }
    }
    return "Veterinarian"; // fallback
}

async function generateStaff() {
    console.log("Connecting to DB...");
    const connection = await mysql.createConnection(dbConfig);

    const staffCount = 1000;
    let staffValues = [];

    for (let i = 0; i < staffCount; i++) {
        const position = weightedRandom(positionWeights);
        
        // Add "Dr." prefix for veterinarians
        let name;
        if (position === "Veterinarian") {
            name = "Dr. " + faker.person.fullName();
        } else {
            name = faker.person.fullName();
        }

        let specialty;
        if (position === "Veterinarian") {
            specialty = faker.helpers.arrayElement(vetSpecialties);
        } else if (position === "Technician") {
            specialty = faker.helpers.arrayElement(techSpecialties);
        } else if (position === "Receptionist") {
            specialty = null;  // Receptionists have no specialty
        } else {
            specialty = "Other";
        }

        const email = `staff${i + 1}@vetclinic.com`;
        const phone = faker.string.numeric(10);
        
        // 95% active, 5% inactive
        const status = Math.random() < 0.95 ? "Active" : "Inactive";

        staffValues.push([
            name,
            position,
            specialty,
            email,
            phone,
            status
        ]);
    }

    console.log(`Inserting ${staffValues.length} staff records...`);

    const sql = `
        INSERT INTO staff
        (name, position, specialty, email, phoneNumber, status)
        VALUES ?
    `;

    await connection.query(sql, [staffValues]);

    console.log(`✓ ${staffValues.length} staff mock data inserted successfully!`);
    
    // Show distribution
    const positionCounts = {};
    staffValues.forEach(s => {
        positionCounts[s[1]] = (positionCounts[s[1]] || 0) + 1;
    });
    
    console.log("\nPosition Distribution:");
    for (const [pos, count] of Object.entries(positionCounts)) {
        const pct = ((count / staffCount) * 100).toFixed(1);
        console.log(`  ${pos}: ${count} (${pct}%)`);
    }

    await connection.end();
}

generateStaff().catch(err => console.error(err));