// generateDiseases.js
// Auto-generate comprehensive disease list for Veterinary Clinic Project
// Based on real veterinary medical services
// This section is generated by AI for the purpose of adding dummy data to the database base on Generateowners.js.

const mysql = require("mysql2/promise");
const { faker } = require("@faker-js/faker");

// ==== MODIFY BELOW FOR YOUR DB ====
const dbConfig = {
    host: "localhost",
    user: "root",
    password: "wjy000908",  // Change this
    database: "vet_clinic",
};
// ==================================

const diseaseData = [
    // General (20)
    ["Annual Checkup", "General", "Routine health examination and vaccination"],
    ["Wellness Exam", "General", "Comprehensive physical examination"],
    ["Vaccination - Rabies", "General", "Rabies vaccination"],
    ["Vaccination - DHPP", "General", "Distemper, hepatitis, parainfluenza, parvovirus"],
    ["Vaccination - FVRCP", "General", "Feline viral rhinotracheitis, calicivirus, panleukopenia"],
    ["Parasite Prevention", "General", "Flea, tick, and heartworm prevention"],
    ["Microchipping", "General", "Pet identification microchip implant"],
    ["Health Certificate", "General", "Travel health certificate"],
    ["Senior Pet Exam", "General", "Geriatric health assessment"],
    ["Puppy/Kitten Exam", "General", "First visit for young pets"],
    ["Blood Work", "General", "Laboratory blood testing"],
    ["Urinalysis", "General", "Urine testing"],
    ["Fecal Test", "General", "Parasite screening"],
    ["Deworming", "General", "Internal parasite treatment"],
    ["Weight Management", "General", "Obesity consultation"],
    ["Nail Trimming", "General", "Nail care"],
    ["Anal Gland Expression", "General", "Gland maintenance"],
    ["Pre-Anesthetic Exam", "General", "Pre-surgery assessment"],
    ["Post-Operative Check", "General", "Surgery follow-up"],
    ["Euthanasia Consultation", "General", "End of life discussion"],

    // Chronic (15)
    ["Diabetes Mellitus", "Chronic", "Blood sugar regulation disorder"],
    ["Arthritis", "Chronic", "Joint inflammation and pain"],
    ["Chronic Kidney Disease", "Chronic", "Chronic renal failure"],
    ["Heart Disease", "Chronic", "Cardiovascular conditions"],
    ["Hyperthyroidism", "Chronic", "Overactive thyroid gland"],
    ["Hypothyroidism", "Chronic", "Underactive thyroid gland"],
    ["Epilepsy", "Chronic", "Seizure disorder"],
    ["Asthma", "Chronic", "Respiratory condition"],
    ["Inflammatory Bowel Disease", "Chronic", "Chronic digestive disorder"],
    ["Cushing Disease", "Chronic", "Hormonal disorder"],
    ["Addison Disease", "Chronic", "Adrenal insufficiency"],
    ["Chronic Pancreatitis", "Chronic", "Pancreatic inflammation"],
    ["Liver Disease", "Chronic", "Hepatic disorder"],
    ["Cancer Treatment", "Chronic", "Oncology care"],
    ["Autoimmune Disease", "Chronic", "Immune system disorder"],

    // Emergency (15)
    ["Poisoning", "Emergency", "Toxic substance ingestion"],
    ["Trauma", "Emergency", "Physical injury"],
    ["Heatstroke", "Emergency", "Severe overheating"],
    ["Bloat/GDV", "Emergency", "Gastric dilatation-volvulus"],
    ["Seizures", "Emergency", "Uncontrolled seizure activity"],
    ["Difficulty Breathing", "Emergency", "Respiratory distress"],
    ["Severe Bleeding", "Emergency", "Hemorrhage"],
    ["Snake Bite", "Emergency", "Venomous bite"],
    ["Hit by Car", "Emergency", "Vehicular trauma"],
    ["Bite Wound", "Emergency", "Animal attack"],
    ["Foreign Body Obstruction", "Emergency", "Airway or GI blockage"],
    ["Urinary Blockage", "Emergency", "Urethral obstruction"],
    ["Eye Injury", "Emergency", "Ocular trauma"],
    ["Severe Allergic Reaction", "Emergency", "Anaphylaxis"],
    ["Electric Shock", "Emergency", "Electrical injury"],

    // Surgical (20)
    ["Spay", "Surgical", "Female sterilization"],
    ["Neuter", "Surgical", "Male sterilization"],
    ["Tumor Removal", "Surgical", "Mass excision"],
    ["Orthopedic Surgery", "Surgical", "Bone and joint surgery"],
    ["Foreign Body Removal", "Surgical", "Surgical removal of ingested objects"],
    ["Bladder Stone Surgery", "Surgical", "Urinary stone removal"],
    ["Hernia Repair", "Surgical", "Hernia correction"],
    ["Eye Surgery", "Surgical", "Ophthalmic procedures"],
    ["Ear Surgery", "Surgical", "Aural hematoma repair"],
    ["Mass Removal", "Surgical", "Soft tissue mass excision"],
    ["C-Section", "Surgical", "Cesarean delivery"],
    ["Laceration Repair", "Surgical", "Wound closure"],
    ["Amputation", "Surgical", "Limb or tail removal"],
    ["Cruciate Ligament Repair", "Surgical", "ACL surgery"],
    ["Hip Dysplasia Surgery", "Surgical", "Hip replacement or FHO"],
    ["Pyometra Surgery", "Surgical", "Uterine infection surgery"],
    ["Intestinal Surgery", "Surgical", "Bowel resection"],
    ["Liver Surgery", "Surgical", "Hepatic procedures"],
    ["Bladder Surgery", "Surgical", "Cystotomy"],
    ["Cherry Eye Repair", "Surgical", "Nictitating membrane surgery"],

    // Dental (12)
    ["Dental Cleaning", "Dental", "Professional teeth cleaning"],
    ["Tooth Extraction", "Dental", "Removal of diseased teeth"],
    ["Periodontal Disease", "Dental", "Gum disease treatment"],
    ["Broken Tooth", "Dental", "Fractured tooth repair"],
    ["Root Canal", "Dental", "Endodontic treatment"],
    ["Oral Tumor", "Dental", "Mouth tumor treatment"],
    ["Gingivitis", "Dental", "Gum inflammation"],
    ["Tooth Abscess", "Dental", "Dental infection"],
    ["Malocclusion", "Dental", "Bite misalignment"],
    ["Retained Teeth", "Dental", "Baby teeth removal"],
    ["Oral Ulcers", "Dental", "Mouth sores"],
    ["Jaw Fracture", "Dental", "Mandibular fracture repair"],

    // Skin (15)
    ["Allergic Dermatitis", "Skin", "Skin inflammation due to allergies"],
    ["Hot Spots", "Skin", "Acute moist dermatitis"],
    ["Mange", "Skin", "Parasitic skin disease"],
    ["Ringworm", "Skin", "Fungal skin infection"],
    ["Skin Infection", "Skin", "Bacterial or yeast infection"],
    ["Ear Infection", "Skin", "Otitis externa or media"],
    ["Abscess", "Skin", "Localized infection"],
    ["Alopecia", "Skin", "Hair loss"],
    ["Seborrhea", "Skin", "Oily or scaly skin"],
    ["Flea Allergy", "Skin", "Flea bite hypersensitivity"],
    ["Contact Dermatitis", "Skin", "Irritant reaction"],
    ["Pyoderma", "Skin", "Bacterial skin infection"],
    ["Yeast Infection", "Skin", "Malassezia dermatitis"],
    ["Skin Cancer", "Skin", "Cutaneous neoplasia"],
    ["Warts", "Skin", "Viral papillomas"],

    // Internal (18)
    ["Gastroenteritis", "Internal", "Stomach and intestinal inflammation"],
    ["Upper Respiratory Infection", "Internal", "URI/cat flu"],
    ["Urinary Tract Infection", "Internal", "Bladder infection"],
    ["Pancreatitis", "Internal", "Pancreas inflammation"],
    ["Pneumonia", "Internal", "Lung infection"],
    ["Anemia", "Internal", "Low red blood cell count"],
    ["Dehydration", "Internal", "Fluid loss"],
    ["Diarrhea", "Internal", "Loose stools"],
    ["Vomiting", "Internal", "Emesis"],
    ["Constipation", "Internal", "Difficulty defecating"],
    ["Colitis", "Internal", "Colon inflammation"],
    ["Hepatitis", "Internal", "Liver inflammation"],
    ["Parvovirus", "Internal", "Canine parvovirus"],
    ["Distemper", "Internal", "Canine distemper virus"],
    ["FeLV", "Internal", "Feline leukemia virus"],
    ["FIV", "Internal", "Feline immunodeficiency virus"],
    ["Kennel Cough", "Internal", "Infectious tracheobronchitis"],
    ["Leptospirosis", "Internal", "Bacterial disease"],

    // Other (10)
    ["Behavioral Consultation", "Other", "Anxiety, aggression, training"],
    ["Nutrition Consultation", "Other", "Dietary guidance"],
    ["Geriatric Care", "Other", "Senior pet management"],
    ["Pregnancy Check", "Other", "Breeding examination"],
    ["Pain Management", "Other", "Chronic pain treatment"],
    ["Rehabilitation", "Other", "Physical therapy"],
    ["Acupuncture", "Other", "Alternative medicine"],
    ["Euthanasia", "Other", "Humane end of life"],
    ["Grooming", "Other", "Professional grooming"],
    ["Boarding", "Other", "Pet boarding services"]
];

async function generateDiseases() {
    console.log("Connecting to DB...");
    const connection = await mysql.createConnection(dbConfig);

    let values = diseaseData.map(([name, category, description]) => [
        name,
        category,
        description
    ]);

    console.log(`Inserting ${values.length} diseases...`);

    const sql = `
        INSERT INTO diseases
        (diseaseName, category, description)
        VALUES ?
    `;

    await connection.query(sql, [values]);

    console.log(`✓ ${values.length} diseases mock data inserted successfully!`);
    
    // Show category distribution
    const categoryCounts = {};
    diseaseData.forEach(d => {
        categoryCounts[d[1]] = (categoryCounts[d[1]] || 0) + 1;
    });
    
    console.log("\nCategory Distribution:");
    for (const [cat, count] of Object.entries(categoryCounts)) {
        console.log(`  ${cat}: ${count}`);
    }

    await connection.end();
}

generateDiseases().catch(console.error);