// generateAdmins.js
// Auto-generate 5 admin accounts for Veterinary Clinic Project
// This section is generated by AI for the purpose of adding dummy data to the database.
const mysql = require("mysql2/promise");

// All admins use same hashed password for "123456"
const hashedPassword = "$2b$10$aPtfSJnr.uPgvMJbvHeKye8IoAfXf53aWpwVDlEoVJA/pIP8nm7vu";

// ==== MODIFY BELOW FOR YOUR DB ====
const dbConfig = {
    host: "localhost",
    user: "root",
    password: "wjy000908", 
    database: "vet_clinic",
};
// ==================================

const adminData = [
    ["admin", hashedPassword, "admin@vetclinic.com"],
    ["superadmin", hashedPassword, "superadmin@vetclinic.com"],
    ["manager", hashedPassword, "manager@vetclinic.com"],
    ["supervisor", hashedPassword, "supervisor@vetclinic.com"],
    ["director", hashedPassword, "director@vetclinic.com"]
];

async function generateAdmins() {
    console.log("Connecting to database...");
    const connection = await mysql.createConnection(dbConfig);

    console.log(`Inserting ${adminData.length} admin accounts...`);

    const sql = `
        INSERT INTO admins
        (username, password, email)
        VALUES ?
    `;

    await connection.query(sql, [adminData]);

    console.log(`✓ ${adminData.length} admin accounts inserted successfully!`);
    console.log("\nAdmin Accounts Created:");
    adminData.forEach(([username, _, email]) => {
        console.log(`  ${username} - ${email} (password: 123456)`);
    });

    await connection.end();
}

generateAdmins().catch(err => {
    console.error("Error:", err);
});