// generateAppointments.js
// Auto-generate 1500 appointments for Veterinary Clinic Project
// All foreign keys properly mapped
// This section is generated by AI for the purpose of adding dummy data to the database base on Generateowners.js.

const mysql = require("mysql2/promise");
const { faker } = require("@faker-js/faker");

// ==== MODIFY BELOW FOR YOUR DB ====
const dbConfig = {
    host: "localhost",
    user: "root",
    password: "wjy000908",  // Change this
    database: "vet_clinic",
};
// ==================================

const appointmentNotes = [
    "Regular checkup scheduled",
    "Follow-up appointment",
    "Owner reports symptoms",
    "Vaccination due",
    "Routine examination",
    "Emergency visit",
    "Post-surgery follow-up",
    "Dental cleaning needed",
    "Behavioral issues reported",
    "Weight loss program",
    "Senior pet wellness check",
    "New patient visit",
    "Medication refill needed",
    "Lab work required",
    "Owner concerned about pet"
];

function getRandomDate(daysBack, daysForward) {
    const today = new Date();
    const minDate = new Date(today);
    minDate.setDate(today.getDate() - daysBack);
    const maxDate = new Date(today);
    maxDate.setDate(today.getDate() + daysForward);
    
    const randomTime = minDate.getTime() + Math.random() * (maxDate.getTime() - minDate.getTime());
    return new Date(randomTime);
}

function formatDate(date) {
    const year = date.getFullYear();
    const month = String(date.getMonth() + 1).padStart(2, '0');
    const day = String(date.getDate()).padStart(2, '0');
    return `${year}-${month}-${day}`;
}

function getRandomTimeSlot() {
    const hours = [9, 10, 11, 13, 14, 15, 16]; // 9 AM - 5 PM, skip 12 PM
    const minutes = ['00', '30'];
    const hour = faker.helpers.arrayElement(hours);
    const minute = faker.helpers.arrayElement(minutes);
    return `${String(hour).padStart(2, '0')}:${minute}:00`;
}

async function generateAppointments() {
    console.log("Connecting to DB...");
    const connection = await mysql.createConnection(dbConfig);

    // Fetch all available IDs
    console.log("Fetching owner IDs...");
    const [owners] = await connection.query("SELECT ownerID FROM owners");
    const ownerIDs = owners.map(o => o.ownerID);

    console.log("Fetching pet IDs...");
    const [pets] = await connection.query("SELECT petID, ownerID FROM Pets");
    
    console.log("Fetching active staff IDs...");
    const [staff] = await connection.query("SELECT staffID FROM staff WHERE status = 'Active'");
    const staffIDs = staff.map(s => s.staffID);

    console.log("Fetching disease IDs...");
    const [diseases] = await connection.query("SELECT diseaseID FROM diseases");
    const diseaseIDs = diseases.map(d => d.diseaseID);

    if (staffIDs.length === 0 || diseaseIDs.length === 0 || pets.length === 0) {
        console.error("❌ Error: Missing required data. Make sure to run other generators first.");
        await connection.end();
        return;
    }

    console.log(`Found ${ownerIDs.length} owners, ${pets.length} pets, ${staffIDs.length} active staff, ${diseaseIDs.length} diseases`);

    const appointmentCount = 1500;
    let appointmentsToInsert = [];

    for (let i = 0; i < appointmentCount; i++) {
        // Random pet and its owner
        const randomPet = faker.helpers.arrayElement(pets);
        const petID = randomPet.petID;
        const ownerID = randomPet.ownerID;

        // Random staff and disease
        const staffID = faker.helpers.arrayElement(staffIDs);
        const diseaseID = faker.helpers.arrayElement(diseaseIDs);

        // Random date within past 180 days to future 180 days
        const appointmentDate = getRandomDate(180, 180);
        const appointmentTime = getRandomTimeSlot();

        // Determine status based on date
        const today = new Date();
        const isInPast = appointmentDate < today;
        const isPastWeek = (today - appointmentDate) / (1000 * 60 * 60 * 24) > 7;

        let status;
        if (isPastWeek) {
            // Past week: mostly completed, some cancelled
            status = Math.random() < 0.9 ? "Completed" : "Cancelled";
        } else if (isInPast) {
            // Recent past: mix of completed and booked
            status = Math.random() < 0.7 ? "Completed" : "Booked";
        } else {
            // Future: booked
            status = "Booked";
        }

        // Random notes (80% have notes)
        const notes = Math.random() < 0.8 
            ? faker.helpers.arrayElement(appointmentNotes)
            : null;

        appointmentsToInsert.push([
            ownerID,
            petID,
            staffID,
            diseaseID,
            formatDate(appointmentDate),
            appointmentTime,
            notes,
            status
        ]);
    }

    console.log(`Inserting ${appointmentsToInsert.length} appointments...`);

    const sql = `
        INSERT INTO appointments
        (ownerID, petID, staffID, diseaseID, appointmentDate, appointmentTime, notes, status)
        VALUES ?
    `;

    await connection.query(sql, [appointmentsToInsert]);

    console.log(`✓ ${appointmentsToInsert.length} appointments mock data inserted successfully!`);

    // Show status distribution
    const statusCounts = {};
    appointmentsToInsert.forEach(a => {
        statusCounts[a[7]] = (statusCounts[a[7]] || 0) + 1;
    });

    console.log("\nAppointment Status Distribution:");
    for (const [status, count] of Object.entries(statusCounts)) {
        const pct = ((count / appointmentCount) * 100).toFixed(1);
        console.log(`  ${status}: ${count} (${pct}%)`);
    }

    await connection.end();
}

generateAppointments().catch(console.error);